# Development environment
name: kaiku-dev

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_NAME: kaiku_dev
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    volumes:
      - ./app/src:/usr/src/app/src

  db:
    image: postgres:16
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dev/db-init:/docker-entrypoint-initdb.d
      - type: volume
        source: kaiku-db
        target: /var/lib/postgresql/data

volumes:
  kaiku-db:
