name: Release new version

on:
  release:
    types:
      - released

jobs:
  tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yaml

  release:
    name: Publish image (latest)
    uses: ./.github/workflows/publish-image.yaml
    with:
      latest: true
    needs:
      - tests
